"""Write and check the committed FeatureTrace maps.

Each tag produces four committed files under the map directory — `<tag>_flow.md`,
`<tag>_mindmap.md`, `<tag>_tour.md`, `<tag>_graph.json` — plus one
`FEATURETRACE_INDEX.md` for all tags.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from textwrap import dedent

from ..config import Config, load_config
from ..core.console import utf8_console
from ..core.files import rel
from . import render
from .model import MarkerNode, scan_all_tags, scan_for_tag
from .settings import UNKNOWN, FTSettings, from_config

INDEX_NAME = "FEATURETRACE_INDEX.md"


def _mermaid_page(settings: FTSettings, kind: str, tag: str, body: str) -> str:
    return (
        f"# FeatureTrace {kind}: `{tag}`\n\n"
        f"> Auto-generated by `{settings.generator_label}`. Do not edit manually.\n\n"
        f"```mermaid\n{body}\n```\n"
    )


def rendered_files_for(settings: FTSettings, tag: str, nodes: list[MarkerNode],
                       out_dir: Path | None = None) -> dict[Path, str]:
    """The four files a tag produces, keyed by path — rendering only, no writing."""
    d = out_dir if out_dir is not None else settings.map_dir
    return {
        d / f"{tag}_flow.md": _mermaid_page(settings, "Flowchart", tag, render.mermaid_flow(settings, nodes, tag)),
        d / f"{tag}_mindmap.md": _mermaid_page(settings, "Mindmap", tag, render.mermaid_mindmap(settings, nodes, tag)),
        d / f"{tag}_tour.md": render.tour(settings, nodes, tag),
        d / f"{tag}_graph.json": render.graph_json(settings, nodes, tag),
    }


def run_check(settings: FTSettings) -> int:
    """Freshness gate for the committed maps and the index. Writes nothing.

    The marker audit checks MARKERS; nothing else checked the generated files, so both
    they and the index rotted quietly — whole tags missing from the index, flowcharts
    short of real nodes. A stale map is worse than a missing one: an incomplete chain
    reads as a complete one.

    Deliberately NOT enforced:

    * Files in the map directory that belong to no current tag. Deleting a tag's maps
      is a judgement call, not a gate's business. Reported, never failed.
    * Files listed in `not_ours` — written by a different generator that happens to
      share a tag's filename prefix. Checking them would demand exactly the output
      that other generator's rule exists to prevent.
    """
    not_ours = {settings.map_dir / name for name in settings.not_ours}
    all_tags = scan_all_tags(settings)

    stale: list[str] = []
    missing: list[str] = []
    for tag in sorted(all_tags):
        for path, body in rendered_files_for(settings, tag, all_tags[tag]).items():
            if path in not_ours:
                continue
            if not path.exists():
                missing.append(rel(path, settings.root))
            elif path.read_text(encoding="utf-8") != body:
                stale.append(rel(path, settings.root))

    index_path = settings.map_dir / INDEX_NAME
    index_stale = (not index_path.exists()
                   or index_path.read_text(encoding="utf-8") != render.index(settings, all_tags))

    known = {p.name for tag in all_tags for p in rendered_files_for(settings, tag, all_tags[tag])}
    orphans = sorted(
        p.name for p in settings.map_dir.glob("*")
        if p.is_file() and p.name != INDEX_NAME and p.name not in known
    )

    print(f"FeatureTrace maps: {len(all_tags)} tag(s), "
          f"{sum(len(v) for v in all_tags.values())} marked file(s)")
    if orphans:
        print(f"  note: {len(orphans)} file(s) in the map directory belong to no "
              f"current tag (not a failure): {', '.join(orphans[:6])}"
              f"{' …' if len(orphans) > 6 else ''}")

    if not (stale or missing or index_stale):
        print("  featuretrace maps: OK (maps and index current)")
        return 0

    print("\nFEATURETRACE MAP CHECK FAILED\n", file=sys.stderr)
    for path in missing:
        print(f"  - MISSING {path}", file=sys.stderr)
    for path in stale:
        print(f"  - STALE   {path}", file=sys.stderr)
    if index_stale:
        print(f"  - STALE   {settings.map_dir_rel}/{INDEX_NAME}", file=sys.stderr)
    print("\n  Regenerate in the same commit as the marker change:", file=sys.stderr)
    print(f"    {settings.command} <tag> --format all --out {settings.map_dir_rel}/", file=sys.stderr)
    print(f"    {settings.command} --index --out {settings.map_dir_rel}/", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None, *, config: Config | None = None,
         settings: FTSettings | None = None, prog: str | None = None) -> int:
    utf8_console()
    s = settings or from_config(config or load_config())
    cmd = s.command
    parser = argparse.ArgumentParser(
        prog=prog,
        description="FeatureTrace Map Generator — CodeSee-equivalent visualization from @featuretrace markers.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=dedent(f"""
            Examples:
              {cmd} news
              {cmd} news --format mindmap
              {cmd} news --format all --out {s.map_dir_rel}/
              {cmd} --list
              {cmd} --index --out {s.map_dir_rel}/
              {cmd} --check
        """),
    )
    parser.add_argument("tag", nargs="?", help="Feature tag to generate map for.")
    parser.add_argument("--format", choices=["mermaid-flow", "mindmap", "tour", "json", "all"],
                        default="all", help="Output format (default: all — prints all formats).")
    parser.add_argument("--out", help="Directory to write output files into (instead of stdout).")
    parser.add_argument("--list", action="store_true",
                        help="List all @featuretrace tags found in the codebase and exit.")
    parser.add_argument("--index", action="store_true",
                        help="Generate a markdown index of all tags. Use --out to write to file.")
    parser.add_argument("--check", action="store_true",
                        help="Compare every committed map file and the index against what this run "
                             "would produce. Writes nothing; exits non-zero on drift.")
    args = parser.parse_args(argv)

    if args.check:
        return run_check(s)

    if args.list:
        all_tags = scan_all_tags(s)
        print(f"Found {len(all_tags)} FeatureTrace tag(s):\n")
        for tag in sorted(all_tags):
            nodes = all_tags[tag]
            layers = sorted({n.layer for n in nodes})
            print(f"  @featuretrace:{tag:<40} {len(nodes):2} files  [{', '.join(layers)}]")
        return 0

    if args.index:
        index_md = render.index(s, scan_all_tags(s))
        if args.out:
            out_dir = Path(args.out)
            out_dir.mkdir(parents=True, exist_ok=True)
            out_file = out_dir / INDEX_NAME
            out_file.write_text(index_md, encoding="utf-8")
            print(f"Written: {out_file}")
        else:
            print(index_md)
        return 0

    if not args.tag:
        parser.error("Provide a tag argument, or use --list / --index.")

    nodes = scan_for_tag(s, args.tag)
    if not nodes:
        # Matched verbatim by the artefact regenerator to tell "no markers" from a crash.
        print(f"No @featuretrace:{args.tag} markers found.", file=sys.stderr)
        return 1

    print(f"Found {len(nodes)} file(s) for @featuretrace:{args.tag}", file=sys.stderr)
    unknown = [n for n in nodes if n.layer == UNKNOWN]
    if unknown:
        print(f"  ⚠  {len(unknown)} file(s) missing 'Layer:' field — "
              "map may be incomplete. Add Layer: to each marker.", file=sys.stderr)
        for n in unknown:
            print(f"     {n.rel_path}:{n.line_no}", file=sys.stderr)

    formats = ["mermaid-flow", "mindmap", "tour", "json"] if args.format == "all" else [args.format]

    if args.out:
        out_dir = Path(args.out)
        out_dir.mkdir(parents=True, exist_ok=True)
        files = rendered_files_for(s, args.tag, nodes, out_dir)
        wanted = {"mermaid-flow": "_flow.md", "mindmap": "_mindmap.md",
                  "tour": "_tour.md", "json": "_graph.json"}
        for fmt in ("mermaid-flow", "mindmap", "tour", "json"):
            if fmt not in formats:
                continue
            path = out_dir / f"{args.tag}{wanted[fmt]}"
            path.write_text(files[path], encoding="utf-8")
            print(f"Written: {path}")
        return 0

    sep = "\n" + "═" * 72 + "\n"
    if "mermaid-flow" in formats:
        print(f"\n{'─'*40}\nMermaid Flowchart\n{'─'*40}")
        print("```mermaid")
        print(render.mermaid_flow(s, nodes, args.tag))
        print("```")
    if "mindmap" in formats:
        print(f"{sep}{'─'*40}\nMermaid Mindmap\n{'─'*40}")
        print("```mermaid")
        print(render.mermaid_mindmap(s, nodes, args.tag))
        print("```")
    if "tour" in formats:
        print(sep)
        print(render.tour(s, nodes, args.tag))
    if "json" in formats:
        print(f"{sep}{'─'*40}\nJSON Graph\n{'─'*40}")
        print(render.graph_json(s, nodes, args.tag))
    return 0
