"""Render one tag's markers as a flowchart, a mindmap, a tour and a JSON graph; all tags as an index."""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Optional

from .model import MarkerNode
from .settings import UNKNOWN, FTSettings

DATA_STORES = "\U0001f5c4 Data Stores"
FEATURE_TOGGLES = "\U0001f500 Feature Toggles"


def safe_id(text: str) -> str:
    """A collision-free Mermaid node identifier.

    Long texts get a stable digest suffix, so two different inputs never truncate to
    the same id — which would draw spurious edges and cycles.
    """
    safe = re.sub(r"[^A-Za-z0-9]", "_", text)
    if len(safe) <= 60:
        return "n_" + safe
    digest = hashlib.md5(text.encode()).hexdigest()[:8]
    return "n_" + safe[:51] + "_" + digest


def mermaid_label(text: str) -> str:
    """Make marker text safe inside a flowchart `["..."]` label.

    A double quote closes the label early and the whole diagram fails to parse; square
    brackets terminate the node shape. The mindmap's `leaf()` defends against `(`
    instead — the two grammars differ, so the two helpers are deliberately separate.
    """
    return text.replace('"', "'").replace("[", "(").replace("]", ")")


def _by_layer(nodes: list[MarkerNode]) -> dict[str, list[MarkerNode]]:
    by_layer: dict[str, list[MarkerNode]] = {}
    for node in nodes:
        by_layer.setdefault(node.layer, []).append(node)
    return by_layer


def _flow_layers(settings: FTSettings, by_layer: dict[str, list[MarkerNode]]) -> list[str]:
    seen = [layer for layer in settings.flow_order if layer in by_layer]
    return seen + [layer for layer in by_layer if layer not in settings.flow_order]


def mermaid_flow(settings: FTSettings, nodes: list[MarkerNode], tag: str) -> str:
    """A Mermaid flowchart (LR): layer subgraphs, data stores, toggles, data-flow and Related edges."""
    if not nodes:
        return f"%% empty — no @featuretrace:{tag} markers found\nflowchart LR"

    lines: list[str] = [
        f"%% featuretrace:{tag} — auto-generated by {settings.generator_label}",
        "flowchart LR",
        "",
    ]
    by_layer = _by_layer(nodes)
    store_nodes: dict[str, str] = {}
    toggle_nodes: dict[str, str] = {}

    for layer in _flow_layers(settings, by_layer):
        spec = settings.layer(layer)
        lines.append(f"    subgraph {safe_id(layer)}[\"{spec.icon} {layer.title()}\"]")
        for node in by_layer[layer]:
            o, c = settings.layer(node.layer).shape
            label = mermaid_label(node.short_name)
            desc_short = (node.description[:50] + "…") if len(node.description) > 50 else node.description
            if desc_short:
                label += f"<br/><small>{mermaid_label(desc_short)}</small>"
            lines.append(f'        {node.node_id}{o}"{label}"{c}')
        lines.append("    end")
        lines.append(f"    style {safe_id(layer)} fill:{spec.fill},color:{spec.text}")
        lines.append("")

    coll_kind, tbl_kind = settings.stores["Collection"], settings.stores["Table"]
    store_lines: list[str] = []
    for node in nodes:
        for coll in node.collections:
            sid = safe_id(f"coll_{coll}")
            if sid not in store_nodes:
                store_nodes[sid] = coll
                store_lines.append(
                    f'        {sid}[("{mermaid_label(coll)}<br/><small>{coll_kind.short}</small>")]')
        for tbl in node.tables:
            sid = safe_id(f"tbl_{tbl}")
            if sid not in store_nodes:
                store_nodes[sid] = tbl
                store_lines.append(
                    f'        {sid}[("{mermaid_label(tbl)}<br/><small>{tbl_kind.short}</small>")]')
    if store_lines:
        lines.append(f"    subgraph n_data[\"{DATA_STORES}\"]")
        lines.extend(store_lines)
        lines.append("    end")
        lines.append("    style n_data fill:#dbeafe,color:#1e3a5f")
        lines.append("")

    toggle_lines: list[str] = []
    for node in nodes:
        if node.toggle:
            tid = safe_id(f"tgl_{node.toggle}")
            if tid not in toggle_nodes:
                toggle_nodes[tid] = node.toggle
                toggle_lines.append(
                    f'        {tid}{{"{mermaid_label(node.toggle)}<br/>feature toggle"}}')
    if toggle_lines:
        lines.append(f"    subgraph n_toggles[\"{FEATURE_TOGGLES}\"]")
        lines.extend(toggle_lines)
        lines.append("    end")
        lines.append("    style n_toggles fill:#fef9c3,color:#854d0e")
        lines.append("")

    # ── Data flow edges: step[0] → step[1] → ... ─────────────────────────────
    lines.append("    %% ── Data flow edges ──────────────────────────────")
    node_by_path: dict[str, str] = {n.rel_path: n.node_id for n in nodes}
    for node in nodes:
        steps = node.data_flow_steps
        if len(steps) < 2:
            continue
        prev_id: Optional[str] = None
        for i, step in enumerate(steps):
            matched_id: Optional[str] = None
            for rel_path, nid in node_by_path.items():
                if Path(rel_path).name in step or rel_path in step:
                    matched_id = nid
                    break
            if matched_id is None:
                # An inline text node, emitted once.
                matched_id = safe_id(f"flow_{node.node_id}_{i}")
                step_clean = step.strip().replace('"', "'")
                if matched_id not in [line.split("[")[0].strip() for line in lines
                                      if line.strip().startswith("n_")]:
                    lines.append(f'    {matched_id}["{step_clean}"]')
            if prev_id:
                lines.append(f"    {prev_id} --> {matched_id}")
            prev_id = matched_id

        for coll in node.collections:
            sid = safe_id(f"coll_{coll}")
            if prev_id and sid in store_nodes:
                lines.append(f"    {prev_id} --> {sid}")
        for tbl in node.tables:
            sid = safe_id(f"tbl_{tbl}")
            if prev_id and sid in store_nodes:
                lines.append(f"    {prev_id} --> {sid}")
        if node.toggle:
            tid = safe_id(f"tgl_{node.toggle}")
            if tid in toggle_nodes:
                lines.append(f"    {node.node_id} -. requires .-> {tid}")

    # ── Related (dashed) edges ────────────────────────────────────────────────
    lines.append("")
    lines.append("    %% ── Related (weak) edges ─────────────────────────")
    emitted: set[tuple[str, ...]] = set()
    for node in nodes:
        for item in node.related_raw:
            rel_name = Path(item.split()[0]).name if "/" in item else item.split()[0]
            target_id: Optional[str] = None
            for rel_path, nid in node_by_path.items():
                if Path(rel_path).name == rel_name or rel_path in item:
                    target_id = nid
                    break
            if target_id and target_id != node.node_id:
                edge_key = tuple(sorted([node.node_id, target_id]))
                if edge_key not in emitted:
                    lines.append(f"    {node.node_id} -.- {target_id}")
                    emitted.add(edge_key)

    lines.append("")
    lines.append("    %% ── Node style classes ───────────────────────────")
    for layer, spec in settings.layers.items():
        nids = [n.node_id for n in nodes if n.layer == layer]
        if nids:
            lines.append(f"    classDef {layer}Class fill:{spec.fill},stroke:#9ca3af,color:{spec.text}")
            lines.append(f"    class {','.join(nids)} {layer}Class")

    return "\n".join(lines)


def mermaid_mindmap(settings: FTSettings, nodes: list[MarkerNode], tag: str) -> str:
    """A Mermaid mindmap: layers, files, descriptions, stores and toggles."""
    if not nodes:
        return f"%% empty — no @featuretrace:{tag} markers found\nmindmap\n  root(({tag}))"

    lines: list[str] = [
        f"%% featuretrace:{tag} — auto-generated by {settings.generator_label}",
        "mindmap",
        f"  root(({tag}))",
    ]

    # Every leaf is `mN["text"]`, never bare text: in the mindmap grammar `(` opens a
    # node shape, so a bare label with parentheses fails the whole diagram — and the
    # store branch below appends "(<kind>)" to every store.
    counter = {"n": 0}

    def leaf(indent: str, text: str) -> str:
        counter["n"] += 1
        safe = text.replace('"', "'").replace("[", "(").replace("]", ")")
        return f'{indent}m{counter["n"]}["{safe}"]'

    by_layer = _by_layer(nodes)
    for layer in _flow_layers(settings, by_layer):
        lines.append(leaf("    ", f"{settings.layer(layer).icon} {layer.title()}"))
        for node in by_layer[layer]:
            lines.append(leaf("      ", node.short_name))
            if node.description:
                desc_short = node.description[:60] + ("…" if len(node.description) > 60 else "")
                lines.append(leaf("        ", desc_short))

    coll_kind, tbl_kind = settings.stores["Collection"], settings.stores["Table"]
    all_colls = list({c for n in nodes for c in n.collections})
    all_tables = list({t for n in nodes for t in n.tables})
    if all_colls or all_tables:
        lines.append(leaf("    ", DATA_STORES))
        for coll in sorted(all_colls):
            lines.append(leaf("      ", f"{coll} ({coll_kind.short})"))
        for tbl in sorted(all_tables):
            lines.append(leaf("      ", f"{tbl} ({tbl_kind.short})"))

    all_toggles = list({n.toggle for n in nodes if n.toggle})
    if all_toggles:
        lines.append(leaf("    ", FEATURE_TOGGLES))
        for tgl in sorted(all_toggles):
            lines.append(leaf("      ", tgl))

    return "\n".join(lines)


def tour(settings: FTSettings, nodes: list[MarkerNode], tag: str) -> str:
    """A markdown walkthrough, one step per file, in layer order."""
    if not nodes:
        return f"_No @featuretrace:{tag} markers found._"

    order = settings.tour_order
    layer_rank = {layer: i for i, layer in enumerate(order)}
    ordered = sorted(nodes, key=lambda n: (layer_rank.get(n.layer, 99), n.rel_path))

    coll_kind, tbl_kind = settings.stores["Collection"], settings.stores["Table"]
    all_colls = sorted({c for n in nodes for c in n.collections})
    all_tables = sorted({t for n in nodes for t in n.tables})
    all_toggles = sorted({n.toggle for n in nodes if n.toggle})
    all_tests = sorted({t for n in nodes for t in n.tests})

    lines: list[str] = [
        f"# FeatureTrace Tour: `{tag}`",
        "",
        f"> **Auto-generated** by `{settings.generator_label}` from `@featuretrace:{tag}` markers.",
        "> Edit the markers in source files; re-run to refresh this tour.",
        "",
        "---",
        "",
        "## Quick Reference",
        "",
        "| Aspect | Detail |",
        "|--------|--------|",
    ]
    if all_toggles:
        lines.append(f"| Feature toggles | {', '.join(f'`{t}`' for t in all_toggles)} |")
    if all_colls:
        lines.append(f"| {coll_kind.long} | {', '.join(f'`{c}`' for c in all_colls)} |")
    if all_tables:
        lines.append(f"| {tbl_kind.long} | {', '.join(f'`{t}`' for t in all_tables)} |")
    if all_tests:
        lines.append(f"| Test files | {', '.join(f'`{t}`' for t in all_tests)} |")
    lines += [
        f"| Files in chain | {len(nodes)} |",
        "",
        "---",
        "",
        "## Step-by-Step Walkthrough",
        "",
    ]

    by_layer = _by_layer(ordered)
    # A layer the tour order does not name still gets its steps. Skipping it is how
    # every `script` file vanished from every tour while the flowchart showed it.
    named = [layer for layer in order if layer in by_layer]
    leftovers = [layer for layer in dict.fromkeys((*settings.flow_order, *by_layer))
                 if layer in by_layer and layer not in order and layer != UNKNOWN]
    step = 1
    for layer in (*named, *leftovers):
        lines.append(f"### {settings.layer(layer).icon} {layer.title()} Layer")
        lines.append("")
        for node in by_layer[layer]:
            lines += [f"**Step {step}** — `{node.rel_path}`", ""]
            if node.description:
                lines.append(f"> {node.description}")
                lines.append("")
            if node.data_flow_raw:
                lines.append(f"**Data flow:** {' → '.join(node.data_flow_steps)}")
                lines.append("")
            if node.related_raw:
                lines.append("**Related files:**")
                for item in node.related_raw:
                    lines.append(f"- `{item}`")
                lines.append("")
            if node.toggle:
                lines.append(f"**Feature toggle:** `{node.toggle}`")
                lines.append("")
            if node.collections:
                lines.append(f"**Collections:** {', '.join(f'`{c}`' for c in node.collections)}")
                lines.append("")
            if node.tables:
                lines.append(f"**Tables:** {', '.join(f'`{t}`' for t in node.tables)}")
                lines.append("")
            lines.append("---")
            lines.append("")
            step += 1

    if UNKNOWN in by_layer:
        lines.append(f"### {settings.layer(UNKNOWN).icon} Uncategorised (add `Layer:` to improve this tour)")
        lines.append("")
        for node in by_layer[UNKNOWN]:
            lines += [
                f"**Step {step}** — `{node.rel_path}`",
                "",
                f"> {node.description or '(no description)'}",
                "",
                "---",
                "",
            ]
            step += 1

    return "\n".join(lines)


def graph_json(settings: FTSettings, nodes: list[MarkerNode], tag: str) -> str:
    """A machine-readable graph: nodes, data-flow and Related edges, stores, toggles."""
    edges: list[dict] = []
    for node in nodes:
        steps = node.data_flow_steps
        for i in range(len(steps) - 1):
            edges.append({
                "from": node.rel_path,
                "to": steps[i + 1],
                "type": "data_flow",
                "label": f"{steps[i]} → {steps[i+1]}",
            })
        for item in node.related_raw:
            edges.append({"from": node.rel_path, "to": item, "type": "related", "label": ""})

    graph = {
        "tag": tag,
        "generated_by": settings.generator_label,
        "node_count": len(nodes),
        "nodes": [n.to_dict() for n in nodes],
        "edges": edges,
        "data_stores": {
            settings.stores["Collection"].json_key: sorted({c for n in nodes for c in n.collections}),
            settings.stores["Table"].json_key: sorted({t for n in nodes for t in n.tables}),
        },
        "feature_toggles": sorted({n.toggle for n in nodes if n.toggle}),
    }
    return json.dumps(graph, indent=2, ensure_ascii=False)


def index(settings: FTSettings, all_tags: dict[str, list[MarkerNode]]) -> str:
    """A markdown index of every tag, plus the layer legend."""
    lines = [
        "# FeatureTrace Index",
        "",
        f"> Auto-generated by `{settings.generator_label} --index`.",
        "> Each tag links to its tour, flowchart, and mindmap.",
        "",
        "| Tag | Files | Layers | Toggles | Collections |",
        "|-----|-------|--------|---------|-------------|",
    ]
    for tag in sorted(all_tags):
        nodes = all_tags[tag]
        layers = sorted({n.layer for n in nodes})
        toggles = sorted({n.toggle for n in nodes if n.toggle})
        colls = sorted({c for n in nodes for c in n.collections})
        lines.append(
            f"| `{tag}` "
            f"| {len(nodes)} "
            f"| {', '.join(layers)} "
            f"| {', '.join(toggles) or '—'} "
            f"| {', '.join(colls) or '—'} |"
        )
    lines += [
        "",
        "## Layer Legend",
        "",
        "| Layer | Icon | Mermaid colour | Description |",
        "|-------|------|----------------|-------------|",
    ]
    for name, spec in settings.layers.items():
        lines.append(f"| `{name}` | {spec.icon} | `{spec.fill}` | {spec.description} |")
    return "\n".join(lines)
