"""Resolve static FastAPI router mounts from already parsed, admitted files."""
from __future__ import annotations

import ast
from collections import defaultdict

from ..scan.python_ast import declared_routers, dependency_names, keyword_value, router_prefix
from .model import Edge, Issue, Node, stable_id


def add_routes(state) -> None:
    from .scanner import _endpoint_id, _symbol_id, normalise_route
    owners = {}
    parents = defaultdict(list)
    for path, tree in state.python_trees.items():
        for name, mount in declared_routers(tree, frozenset({"APIRouter", "FastAPI"})).items():
            owners[(path, name)] = mount
    for path, tree in state.python_trees.items():
        for call in ast.walk(tree):
            if not (isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute)
                    and call.func.attr == "include_router" and call.args):
                continue
            if not isinstance(call.func.value, ast.Name):
                continue
            parent = (path, call.func.value.id)
            arg = call.args[0]
            child = (path, arg.id) if isinstance(arg, ast.Name) else None
            if child not in owners:
                local = arg.id if isinstance(arg, ast.Name) else arg.value.id if isinstance(arg, ast.Attribute) and isinstance(arg.value, ast.Name) else ""
                binding = state.imports.get(path, {}).get(local)
                if binding:
                    target, symbol = binding
                    child = (target, arg.attr if isinstance(arg, ast.Attribute) else symbol)
            if parent not in owners or child not in owners:
                state.graph.issues.append(Issue(
                    "UNRESOLVED_ROUTER_MOUNT", "warning", "A FastAPI router mount could not be resolved statically.",
                    [], f"{path}:{call.lineno}", "Review router factories, dynamic includes, and import aliases.",
                ))
                continue
            parents[child].append((parent, router_prefix(call), dependency_names(keyword_value(call, "dependencies"))))

    def mounts(key, seen=()):
        own = owners[key]
        if key in seen or len(seen) >= 30:
            return []
        if not parents[key]:
            return [(own.prefix, own.dependencies)]
        result = []
        for parent, prefix, deps in parents[key]:
            for parent_prefix, parent_deps in mounts(parent, (*seen, key)):
                result.append((parent_prefix + prefix + own.prefix, (*parent_deps, *deps, *own.dependencies)))
                if len(result) >= 100:
                    return result
        return result

    for path, tree in state.python_trees.items():
        # These are the same qualified names generated by PythonVisitor.
        from ..scan.python_ast import functions
        for function, qualified in functions(tree):
            symbol = _symbol_id(path, qualified)
            if symbol not in state.graph.nodes:
                continue
            for dec in function.decorator_list:
                if not (isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute)
                        and isinstance(dec.func.value, ast.Name) and dec.args
                        and isinstance(dec.args[0], ast.Constant) and isinstance(dec.args[0].value, str)):
                    continue
                method = dec.func.attr.upper()
                if method not in {"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "TRACE"}:
                    continue
                key = (path, dec.func.value.id)
                declared = owners.get(key)
                # Preserve bare router fixtures, but distinguish an inferred receiver.
                variants = mounts(key) if declared else [("", ())]
                if not variants:
                    state.graph.issues.append(Issue("ROUTER_MOUNT_CYCLE", "warning", "Router mount cycle prevented route resolution.",
                                                  [symbol], f"{path}:{dec.lineno}", "Remove cyclic router includes."))
                for prefix, deps in variants:
                    route = normalise_route(state.config.backend_api_prefix + prefix + dec.args[0].value)
                    endpoint = _endpoint_id(method, route)
                    state.graph.add_node(Node(endpoint, "endpoint", f"{method} {route}", path=path, line=dec.lineno,
                                              language="python", metadata={"method": method, "route": route,
                                                                          "framework": "fastapi", "dependencies": list(deps)}))
                    state.graph.add_edge(Edge(endpoint, symbol, "HANDLES_API", "exact" if declared else "probable",
                                              f"{path}:{dec.lineno}", origin="python_ast",
                                              detail="Static router mount; runtime registration not executed"))
