"""Register the `generated` merge driver and the post-merge hooks, for ONE clone.

Two pieces, and they do different jobs:

  merge driver       resolves without a conflict by keeping one side. It does NOT try to
                     be correct — the content is replaced straight afterwards. This is what
                     removes an unmergeable single-line conflict on a large generated file.

  post-merge /       regenerate from the COMPLETED tree. This is where correctness comes
  post-rewrite hooks from. See `repolens.artefacts.regenerate` for why the driver itself
                     must never regenerate.

Git stores driver definitions and hooks outside the versioned tree, so `.gitattributes`
can NAME a driver but cannot supply it; this has to run once per clone. Safe to re-run.
"""
from __future__ import annotations

import argparse
import os
import shlex
import shutil
import stat
from pathlib import Path

from ..core.git import run_git
from ..config import Config
from .settings import ArtefactSettings, from_config

HOOKS = ("post-merge", "post-rewrite")

HOOK_TEMPLATE = """#!/usr/bin/env bash
# Installed by repolens (artefacts install-hooks) - regenerate derived artefacts from
# the completed tree. Never fails the operation: a hook that aborts leaves a developer
# stranded mid-merge, and the CI gate is the real backstop.
{command} --changed-since 'HEAD@{{1}}' --quiet || true
"""


def _python() -> str:
    """The interpreter the hooks call: $PYTHON, else python3, else python."""
    explicit = os.environ.get("PYTHON")
    if explicit:
        return explicit
    return "python3" if shutil.which("python3") else "python"


def hook_body(settings: ArtefactSettings) -> str:
    """The script written to each hook: `hook_command` with `{python}` filled in, never failing."""
    # Quoted: an interpreter under a path with a space otherwise splits into two words,
    # the hook fails, and `|| true` swallows it — nothing regenerated, nothing reported.
    return HOOK_TEMPLATE.format(command=settings.hook_command.replace("{python}", shlex.quote(_python())))


def _git(root: Path, *args: str) -> str:
    return run_git(root, *args, check=True, timeout=60).stdout.strip()


def install(settings: ArtefactSettings) -> list[str]:
    """Register the driver and write the hooks. Returns the lines to print."""
    root = settings.root
    driver = settings.driver
    _git(root, "config", f"merge.{driver}.name",
         "keep one side; the artefact is regenerated by the post-merge hook")
    # `true` succeeds and leaves %A (ours) in place: no conflict, no pretence of correctness.
    _git(root, "config", f"merge.{driver}.driver", "true")

    hooks_dir = Path(_git(root, "rev-parse", "--git-path", "hooks"))
    if not hooks_dir.is_absolute():
        hooks_dir = root / hooks_dir
    hooks_dir.mkdir(parents=True, exist_ok=True)
    body = hook_body(settings)
    for name in HOOKS:
        hook = hooks_dir / name
        # LF on every platform: a `bash\r` shebang does not run.
        hook.write_text(body, encoding="utf-8", newline="\n")
        hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    return [
        f"Installed for {root}:",
        f"  merge driver '{driver}'   (git config merge.{driver}.driver)",
        f"  hooks: {', '.join(HOOKS)} -> {settings.hook_command.replace('{python}', _python())}",
        "",
        f"Applies to the paths marked merge={driver} in .gitattributes.",
        "",
        "NOT installing this breaks nothing. Git falls back to a normal three-way merge,",
        "you get an ordinary conflict, and the CI gate still catches a stale artefact.",
        "Resolve one by regenerating, never by hand:",
        "  git checkout --ours <path>",
        f"  {settings.command} --all --include-slow",
        "",
        "A merge performed by GitHub's merge button runs NO client hooks at all, so the",
        "CI gate is the only thing protecting a server-side merge.",
    ]


def main(argv: list[str] | None = None, *, config: Config | None = None,
         settings: ArtefactSettings | None = None, prog: str | None = None) -> int:
    """Entry point for `repolens artefacts install-hooks`: install for this clone, print the summary."""
    argparse.ArgumentParser(prog=prog, description=__doc__,
                            formatter_class=argparse.RawDescriptionHelpFormatter).parse_args(argv)
    for line in install(settings or from_config(config)):
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
